#######################################################
# 
# FeatureComputer.py
# Python implementation of the Class FeatureComputer
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import numpy as np
import pandas as pd


class FeatureComputer:

    FEATURE_NAMES = [
        "motion_disagreement",
        "motion_mismatch",
        "speed_per_dyn_mag",
        "speed_per_jerk_std",
    ]

    MOVING_SPEED_THRESHOLD = 1.0      # km/h
    MOVING_DYN_MAG_THRESHOLD = 0.04   # g

    def _motion_disagreement(self, speed, dyn_mag):
        gps_moving = speed > self.MOVING_SPEED_THRESHOLD
        accel_moving = dyn_mag > self.MOVING_DYN_MAG_THRESHOLD
        return int(gps_moving != accel_moving)

    def _motion_mismatch(self, speed, dyn_mag):
        return abs((speed / 100.0) - (dyn_mag * 2.0))

    def _speed_per_dyn_mag(self, speed, dyn_mag):
        return speed / (dyn_mag + 0.001)

    def _speed_per_jerk_std(self, speed, jerk_std):
        return speed / (jerk_std + 0.01)

    def compute_one(self, speed, dyn_mag, jerk_std):
        return {
            "motion_disagreement": self._motion_disagreement(speed, dyn_mag),
            "motion_mismatch": self._motion_mismatch(speed, dyn_mag),
            "speed_per_dyn_mag": self._speed_per_dyn_mag(speed, dyn_mag),
            "speed_per_jerk_std": self._speed_per_jerk_std(speed, jerk_std),
        }

    def compute_batch(self, df):
        gps_moving = df["Speed"] > self.MOVING_SPEED_THRESHOLD
        accel_moving = df["Dynamic Magnitude"] > self.MOVING_DYN_MAG_THRESHOLD

        df["motion_disagreement"] = (gps_moving != accel_moving).astype(int)
        df["motion_mismatch"] = (
            (df["Speed"] / 100.0) - (df["Dynamic Magnitude"] * 2.0)
        ).abs()
        df["speed_per_dyn_mag"] = df["Speed"] / (df["Dynamic Magnitude"] + 0.001)
        df["speed_per_jerk_std"] = df["Speed"] / (df["Jerk Std"] + 0.01)

        return df
