#######################################################
# 
# ModeReader.py
# Python implementation of the Class ModeReader
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

DEFAULT_MODE_PATH = '/sd/mode.txt'


class ModeReader:
    """Reads /sd/mode.txt to select record or replay mode."""

    def __init__(self, path=DEFAULT_MODE_PATH):
        self.path = path

    def read_mode(self):
        try:
            f = open(self.path, 'r')
            content = f.read().strip()
            f.close()

            if content == 'record':
                return ('record', None)
            elif content.startswith('replay:'):
                filename = content.split(':', 1)[1].strip()
                return ('replay', filename)
            else:
                print("Invalid mode.txt, defaulting to record")
                return ('record', None)

        except Exception:
            print("No mode.txt found, defaulting to record")
            return ('record', None)
