#######################################################
# 
# RouteCsv.py
# Python implementation of the Class RouteCsv
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

#
# RouteCsv.py
# Handles the route CSV file on the spoofer SD card. Used in both modes:
#   - record mode writes the header + one row per fix
#   - replay mode loads rows back into a list of GPS dicts
#
# Three header schemas are accepted on load so old route files still
# replay after the schema change:
#   NEW (12 cols, Device-A aligned): "Time, UTC Date, UTC Time, Label, Latitude, ..."
#   MID (10 cols):                    "utc_date,utc_time,lat,lon,..."
#   OLD ( 9 cols):                    "utc_time,lat,lon,..."
# Writes only ever use the NEW schema.
#

import time


# Must stay byte-for-byte equal to Device A's GPS-only column subset so
# the two devices' logs are directly concatenable / comparable.
RECORD_CSV_HEADER = (
    "Time, UTC Date, UTC Time, Label, Latitude, Longitude, Altitude,"
    " Speed, HDOP, Satelites, Course, Fix\n"
)


class RouteCsv:

    def __init__(self, file_path):
        self.file_path = file_path

    def write_header(self):
        # Truncates any existing file and drops in the header row
        with open(self.file_path, 'w') as f:
            f.write(RECORD_CSV_HEADER)

    def write_row(self, gps_data, label):
        # Same comma-no-space data-row style as Device A's build_log_line(),
        # so a row from this device parses with the same CSV reader code as
        # a row from Device A (just with the accel columns absent).
        line = "{},{},{},{},{},{},{},{},{},{},{},{}\n".format(
            time.time(),
            gps_data.get('utc_date', ''),
            gps_data['utc_time'],
            label,
            gps_data['lat'],
            gps_data['lon'],
            gps_data['alt'],
            gps_data['speed'],
            gps_data['hdop'],
            gps_data['sats'],
            gps_data['course'],
            gps_data['fix'],
        )
        with open(self.file_path, 'a') as f:
            f.write(line)

    def load_route(self):
        # Returns a list of GPS dicts. Empty list on any error.
        route = []
        try:
            f = open(self.file_path, 'r')
            lines = f.read().split('\n')
            f.close()

            if not lines:
                print("Empty route file")
                return []

            header = lines[0].strip().lower()
            schema = self._detect_schema(header)
            print("Route header schema: {}".format(schema))

            for line in lines[1:]:
                line = line.strip()
                if not line:
                    continue

                try:
                    parts = [p.strip() for p in line.split(',')]
                    if schema == 'new':
                        # Time(0), UTC Date(1), UTC Time(2), Label(3),
                        # Lat(4), Lon(5), Alt(6), Speed(7), HDOP(8),
                        # Sats(9), Course(10), Fix(11)
                        utc_date = parts[1]
                        utc_time = parts[2]
                        lat = float(parts[4])
                        lon = float(parts[5])
                        alt = float(parts[6])
                        speed = float(parts[7])
                        hdop = float(parts[8])
                        sats = int(parts[9])
                        course = float(parts[10])
                        fix = int(parts[11])
                    elif schema == 'mid':
                        utc_date = parts[0]
                        utc_time = parts[1]
                        lat = float(parts[2])
                        lon = float(parts[3])
                        alt = float(parts[4])
                        speed = float(parts[5])
                        hdop = float(parts[6])
                        sats = int(parts[7])
                        course = float(parts[8])
                        fix = int(parts[9])
                    else:  # old
                        utc_date = ''
                        utc_time = parts[0]
                        lat = float(parts[1])
                        lon = float(parts[2])
                        alt = float(parts[3])
                        speed = float(parts[4])
                        hdop = float(parts[5])
                        sats = int(parts[6])
                        course = float(parts[7])
                        fix = int(parts[8])

                    route.append({
                        'utc_date': utc_date,
                        'utc_time': utc_time,
                        'lat': lat,
                        'lon': lon,
                        'alt': alt,
                        'speed': speed,
                        'hdop': hdop,
                        'sats': sats,
                        'course': course,
                        'fix': fix,
                    })
                except Exception as e:
                    print("Skipping bad route line:", e)
                    continue

            print("Loaded {} route points".format(len(route)))
            return route

        except Exception as e:
            print("Failed to load route:", e)
            return []

    def _detect_schema(self, header):
        # NEW has both "label" and "latitude". MID has "utc_date" but no
        # "label". OLD has only "utc_time". This lets old recordings keep
        # working without manual conversion.
        if 'label' in header and 'latitude' in header:
            return 'new'
        elif 'utc_date' in header:
            return 'mid'
        else:
            return 'old'
