#######################################################
# 
# RouteReplayer.py
# Python implementation of the Class RouteReplayer
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import pycom
from time import sleep

from GPS_spoofer.RouteCsv import RouteCsv


REPLAY_INTERVAL_S = 2.5


class RouteReplayer:

    def __init__(self, lora_tx, label=1):
        self.lora_tx = lora_tx
        self.label = label
        self.route = []
        self.idx = 0
        self.direction = 1
        self.packet_count = 0

    def load_route(self, filename):
        csv = RouteCsv("/sd/{}".format(filename))
        self.route = csv.load_route()
        if not self.route:
            print("No route loaded. Check filename in mode.txt.")
            return False
        return True

    def run(self):
        if not self.route:
            print("No route loaded - call load_route() first.")
            return

        print("Replaying {} points on loop. Ctrl+C to stop".format(len(self.route)))
        pycom.rgbled(0x800000)

        while True:
            gps_data = self.route[self.idx]
            self.idx += self.direction

            if self.idx >= len(self.route):
                self.idx = len(self.route) - 2 if len(self.route) > 1 else 0
                self.direction = -1
                print("Route reversing...")
            elif self.idx < 0:
                self.idx = 1 if len(self.route) > 1 else 0
                self.direction = 1
                print("Route reversing...")

            success = self.lora_tx.send_gps(gps_data, self.label)

            if success:
                self.packet_count += 1
                pycom.rgbled(0x800000)
                print("Replayed point {}/{} - {:.6f}, {:.6f}".format(
                    self.idx, len(self.route), gps_data['lat'], gps_data['lon']))
            else:
                print("Send failed")
                pycom.rgbled(0x000000)
                sleep(0.1)
                pycom.rgbled(0x800000)

            if self.packet_count > 0 and self.packet_count % 10 == 0:
                stats = self.lora_tx.get_stats()
                print("Stats:", stats)

            sleep(REPLAY_INTERVAL_S)
