#######################################################
# 
# AccelCalibration.py
# Python implementation of the Class AccelCalibration
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import time
import math


CALIBRATION_SAMPLES = 200
SAMPLE_DELAY_MS = 10
GRAVITY_REFERENCE = 1.0
GRAVITY_TOLERANCE = 0.15  # g


class AccelCalibration:
    """Per-axis accelerometer bias correction."""

    def __init__(self):
        self.bias_x = 0.0
        self.bias_y = 0.0
        self.bias_z = 0.0
        self.is_calibrated = False

    def calibrate(self, accel, num_samples=CALIBRATION_SAMPLES):
        sum_x = 0.0
        sum_y = 0.0
        sum_z = 0.0

        print("Calibrating accelerometer - keep the device STILL (level not required)")

        for _ in range(num_samples):
            ax, ay, az = accel.acceleration()
            sum_x += ax
            sum_y += ay
            sum_z += az
            time.sleep_ms(SAMPLE_DELAY_MS)

        mean_x = sum_x / num_samples
        mean_y = sum_y / num_samples
        mean_z = sum_z / num_samples

        mean_mag = math.sqrt(mean_x * mean_x + mean_y * mean_y + mean_z * mean_z)

        if mean_mag < 1e-6:
            print("WARNING: mean |a| near zero, calibration skipped")
            self.bias_x = 0.0
            self.bias_y = 0.0
            self.bias_z = 0.0
            self.is_calibrated = False
            return (self.bias_x, self.bias_y, self.bias_z)

        unit_x = mean_x / mean_mag
        unit_y = mean_y / mean_mag
        unit_z = mean_z / mean_mag

        self.bias_x = mean_x - unit_x * GRAVITY_REFERENCE
        self.bias_y = mean_y - unit_y * GRAVITY_REFERENCE
        self.bias_z = mean_z - unit_z * GRAVITY_REFERENCE

        self.is_calibrated = True

        print("Calibration complete")
        print("  Mean |a|: {:.4f} g (expected ~1.000)".format(mean_mag))
        print("  Bias X: {:.6f}".format(self.bias_x))
        print("  Bias Y: {:.6f}".format(self.bias_y))
        print("  Bias Z: {:.6f}".format(self.bias_z))

        if abs(mean_mag - GRAVITY_REFERENCE) > GRAVITY_TOLERANCE:
            print("WARNING: |a| deviates from 1 g by more than {:.2f} -".format(GRAVITY_TOLERANCE))
            print("         device was likely moving or sensor scale is wrong.")
            print("         Redo calibration with the device sitting still.")

        return (self.bias_x, self.bias_y, self.bias_z)

    def apply(self, raw_x, raw_y, raw_z):
        if not self.is_calibrated:
            return (raw_x, raw_y, raw_z)

        return (
            raw_x - self.bias_x,
            raw_y - self.bias_y,
            raw_z - self.bias_z,
        )
