#######################################################
# 
# JerkCalculation.py
# Python implementation of the Class JerkCalculation
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

#
# JerkCalculation.py
# Jerk is the rate of change of acceleration (derivative of accel over time).
# It captures how sharply acceleration changes, which is useful for catching
# motion that doesn't match a vehicle's natural inertia. Renamed from
# VectorJerk -> JerkCalculation for the diagram.
#

import math
import time


# Sanity bounds:
# MIN_DT_MS - at 100 Hz ODR the expected dt is ~10 ms. Anything below is
#   suspicious (double-read or ticks_ms artifact).
# MAX_DT_MS - if dt > 1 s the previous state is stale (cross-burst carryover
#   or paused main loop). Reset instead of dividing by something huge.
# MAX_JERK - 1000 g/s would mean 0 to 100 g in 0.1 s, beyond any real
#   vehicle motion. Clamp to protect downstream windowed stats from
#   transient spikes during EMA warmup or sensor glitches.
MIN_DT_MS = 2
MAX_DT_MS = 1000
MAX_JERK = 1000.0


class JerkCalculation:

    def __init__(self):
        # Last sample we saw, kept around for the delta calculation
        self.prev_x = None
        self.prev_y = None
        self.prev_z = None
        self.prev_time_ms = None

    def reset(self):
        # Clear previous state so the next update() re-seeds.
        # Called at the start of each accel burst.
        self.prev_x = None
        self.prev_y = None
        self.prev_z = None
        self.prev_time_ms = None

    def update(self, dyn_x, dyn_y, dyn_z, current_time_ms):
        # Compute jerk from current and previous acceleration values.
        if current_time_ms is None:
            current_time_ms = time.ticks_ms()

        if self.prev_x is None:
            self.prev_x = dyn_x
            self.prev_y = dyn_y
            self.prev_z = dyn_z
            self.prev_time_ms = current_time_ms
            return None

        dt_ms = time.ticks_diff(current_time_ms, self.prev_time_ms)

        # Stale previous state (paused loop, cross-burst carryover, or
        # ticks_ms rollover edge). Re-seed and skip this sample.
        if dt_ms <= 0 or dt_ms > MAX_DT_MS:
            self.prev_x = dyn_x
            self.prev_y = dyn_y
            self.prev_z = dyn_z
            self.prev_time_ms = current_time_ms
            return None

        # Floor dt to keep the quotient sane on abnormally fast reads
        if dt_ms < MIN_DT_MS:
            dt_ms = MIN_DT_MS

        dt_s = dt_ms / 1000.0

        jerk_x = (dyn_x - self.prev_x) / dt_s
        jerk_y = (dyn_y - self.prev_y) / dt_s
        jerk_z = (dyn_z - self.prev_z) / dt_s

        jerk_mag = math.sqrt(jerk_x * jerk_x + jerk_y * jerk_y + jerk_z * jerk_z)

        # Clamp pathological spikes
        if jerk_mag > MAX_JERK:
            jerk_mag = MAX_JERK

        self.prev_x = dyn_x
        self.prev_y = dyn_y
        self.prev_z = dyn_z
        self.prev_time_ms = current_time_ms

        return {
            'jerk': (jerk_x, jerk_y, jerk_z),
            'jerk_magnitude': jerk_mag,
        }
