#######################################################
# 
# JerkCalculation.py
# Python implementation of the Class JerkCalculation
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import math
import time


MIN_DT_MS = 2
MAX_DT_MS = 1000
MAX_JERK = 1000.0


class JerkCalculation:

    def __init__(self):
        self.prev_x = None
        self.prev_y = None
        self.prev_z = None
        self.prev_time_ms = None

    def reset(self):
        self.prev_x = None
        self.prev_y = None
        self.prev_z = None
        self.prev_time_ms = None

    def update(self, dyn_x, dyn_y, dyn_z, current_time_ms):
        if current_time_ms is None:
            current_time_ms = time.ticks_ms()

        if self.prev_x is None:
            self.prev_x = dyn_x
            self.prev_y = dyn_y
            self.prev_z = dyn_z
            self.prev_time_ms = current_time_ms
            return None

        dt_ms = time.ticks_diff(current_time_ms, self.prev_time_ms)

        # stale previous state, re-seed and skip
        if dt_ms <= 0 or dt_ms > MAX_DT_MS:
            self.prev_x = dyn_x
            self.prev_y = dyn_y
            self.prev_z = dyn_z
            self.prev_time_ms = current_time_ms
            return None

        if dt_ms < MIN_DT_MS:
            dt_ms = MIN_DT_MS

        dt_s = dt_ms / 1000.0

        jerk_x = (dyn_x - self.prev_x) / dt_s
        jerk_y = (dyn_y - self.prev_y) / dt_s
        jerk_z = (dyn_z - self.prev_z) / dt_s

        jerk_mag = math.sqrt(jerk_x * jerk_x + jerk_y * jerk_y + jerk_z * jerk_z)

        if jerk_mag > MAX_JERK:
            jerk_mag = MAX_JERK

        self.prev_x = dyn_x
        self.prev_y = dyn_y
        self.prev_z = dyn_z
        self.prev_time_ms = current_time_ms

        return {
            'jerk': (jerk_x, jerk_y, jerk_z),
            'jerk_magnitude': jerk_mag,
        }
