#######################################################
# 
# SdLogger.py
# Python implementation of the Class SdLogger
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import os
import time
from machine import SD


CSV_HEADER = (
    "Time, UTC Date, UTC Time, Label, Latitude, Longitude, Altitude, Speed, HDOP, Satelites, Course, Fix,"
    " Roll Degrees, Pitch Degrees, Dynamic Magnitude, Jerk, Jerk Std, Acceleration X, Acceleration Y, Acceleration Z,"
    " Standard Deviation, Energy, Zero Crossings\n"
)

RAW_ACCEL_HEADER = (
    "ts_ms,sample_idx,raw_x,raw_y,raw_z,cal_x,cal_y,cal_z,"
    "world_x,world_y,world_z,dyn_mag,roll_deg,pitch_deg\n"
)


class SdLogger:

    def __init__(self, timestamp):
        self.log_path = "/sd/gps_log_A_{}.csv".format(timestamp)
        self.raw_accel_path = "/sd/accel_raw_A_{}.csv".format(timestamp)

        self.log_handle = None
        self.raw_handle = None

        with open(self.log_path, "w") as f:
            f.write(CSV_HEADER)
        with open(self.raw_accel_path, "w") as f:
            f.write(RAW_ACCEL_HEADER)

    @classmethod
    def mount(cls):
        sd = SD()
        try:
            os.mount(sd, '/sd')
        except OSError as e:
            print("SD mount note:", e)

    def write_log_row(self, gps, accel, label):
        line = self._build_log_line(gps, accel, label)
        try:
            with open(self.log_path, "a") as f:
                f.write(line)
        except Exception as e:
            print("SD write error:", e)

    def write_raw_accel_row(self, ts_ms, sample_idx, raw_row):
        try:
            with open(self.raw_accel_path, "a") as f:
                f.write(
                    "{},{},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f},{:.6f}\n".format(
                        ts_ms, sample_idx,
                        raw_row['raw_x'], raw_row['raw_y'], raw_row['raw_z'],
                        raw_row['cal_x'], raw_row['cal_y'], raw_row['cal_z'],
                        raw_row['world_x'], raw_row['world_y'], raw_row['world_z'],
                        raw_row['dyn_mag'], raw_row['roll_deg'], raw_row['pitch_deg'],
                    )
                )
        except Exception as e:
            print("Raw accel SD write error:", e)

    def close(self):
        self.log_handle = None
        self.raw_handle = None

    @staticmethod
    def _build_log_line(gps, accel, label):
        def safe(val):
            if val is None:
                return ''
            return '{:.6f}'.format(val)

        def safe_gps(val):
            if val is None:
                return ''
            return str(val)

        a = accel if accel is not None else {}

        return "{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}\n".format(
            time.time(),
            gps.get('utc_date', '') or '',
            gps.get('utc_time', '') or '',
            label,
            safe_gps(gps.get('lat')),
            safe_gps(gps.get('lon')),
            safe_gps(gps.get('alt')),
            safe_gps(gps.get('speed')),
            safe_gps(gps.get('hdop')),
            gps.get('sats', 0),
            safe_gps(gps.get('course')),
            gps.get('fix', 0),
            safe(a.get('roll')),
            safe(a.get('pitch')),
            safe(a.get('dyn_mag')),
            safe(a.get('jerk_mag')),
            safe(a.get('jerk_std')),
            safe(a.get('accel_x')),
            safe(a.get('accel_y')),
            safe(a.get('accel_z')),
            safe(a.get('accel_std')),
            safe(a.get('accel_energy')),
            safe(a.get('accel_zero_cross')),
        )
