#######################################################
# 
# WindowStats.py
# Python implementation of the Class WindowStats
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import math


class WindowStats:
    """Rolling-window statistics over a fixed-size circular buffer."""

    def __init__(self, window_size=10):
        self.window_size = window_size

        self.buffer = [0.0] * window_size
        self.index = 0
        self.count = 0
        self.is_full = False

    def add_sample(self, value):
        self.buffer[self.index] = value
        self.index = (self.index + 1) % self.window_size
        self.count += 1

        if self.count >= self.window_size:
            self.is_full = True

    def compute(self):
        if not self.is_full:
            return None

        n = self.window_size

        total = 0.0
        for i in range(n):
            total += self.buffer[i]
        mean = total / n

        var_sum = 0.0
        for i in range(n):
            diff = self.buffer[i] - mean
            var_sum += diff * diff
        variance = var_sum / n
        std_dev = math.sqrt(variance)

        min_val = self.buffer[0]
        max_val = self.buffer[0]
        for i in range(n):
            if self.buffer[i] < min_val:
                min_val = self.buffer[i]
            if self.buffer[i] > max_val:
                max_val = self.buffer[i]

        energy = 0.0
        for i in range(n):
            energy += self.buffer[i] * self.buffer[i]
        energy = energy / n

        crossings = 0
        for i in range(1, n):
            if (self.buffer[i - 1] > 0 and self.buffer[i] <= 0) or \
               (self.buffer[i - 1] <= 0 and self.buffer[i] > 0):
                crossings += 1

        return {
            'mean': mean,
            'std_dev': std_dev,
            'min_val': min_val,
            'max_val': max_val,
            'range_val': max_val - min_val,
            'energy': energy,
            'zero_crossings': crossings,
            'window_full': True,
        }
