#######################################################
# 
# AccumulationResult.py
# Python implementation of the Class AccumulationResult
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import os
from dataclasses import dataclass, field

import matplotlib.pyplot as plt
import pandas as pd


@dataclass
class AccumulationResult:
    k_values: list = field(default_factory=list)
    accuracies: list = field(default_factory=list)
    ranked_features: list = field(default_factory=list)
    max_accuracy: float = 0.0
    optimal_k: int = 0
    delta_tolerance: float = 0.01

    def plot(self, save_path):
        save_dir = os.path.dirname(save_path)
        if save_dir:
            os.makedirs(save_dir, exist_ok=True)

        plt.figure(figsize=(8, 5))
        plt.plot(self.k_values, self.accuracies,
                 marker='o', color='steelblue', linewidth=2)
        plt.xlabel('Number of features (top-k by ranking)')
        plt.ylabel('Validation accuracy')
        plt.title('Feature Accumulation Curve')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(save_path, dpi=120, bbox_inches='tight')
        plt.close()

    def to_dataframe(self):
        return pd.DataFrame({
            "k": self.k_values,
            "accuracy": self.accuracies,
        })
