#######################################################
# 
# CombinedRanking.py
# Python implementation of the Class CombinedRanking
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass, field


@dataclass
class CombinedRanking:
    feature_names: list = field(default_factory=list)
    combined_ranks: list = field(default_factory=list)
    combined_scores: list = field(default_factory=list)
    method_used: str = ""

    def top_k_features(self, k):
        if not self.feature_names:
            return []
        pairs = sorted(
            zip(self.feature_names, self.combined_ranks),
            key=lambda kv: kv[1],
        )
        return [name for name, _ in pairs[:k]]
