#######################################################
# 
# DatasetMerger.py
# Python implementation of the Class DatasetMerger
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import glob
import os

import pandas as pd

from Pc_backend.Pc_common.FeatureComputer import FeatureComputer


class DatasetMerger:

    def __init__(self, data_dir, out_dir, feature_cols, holdout_tokens):
        self.data_dir = data_dir
        self.out_dir = out_dir
        self.feature_cols = list(feature_cols)
        self.holdout_tokens = list(holdout_tokens)
        self.features = FeatureComputer()

    @staticmethod
    def _session_id_from_filename(path):
        return os.path.splitext(os.path.basename(path))[0]

    def _is_holdout_session(self, session_id):
        return any(tok in session_id for tok in self.holdout_tokens)

    def _load_one_file(self, path):
        df = pd.read_csv(path)

        # Some firmware versions wrote headers with a leading space
        df.columns = [c.strip() for c in df.columns]

        if "UTC Date" in df.columns:
            df["utc"] = df["UTC Date"].astype(str) + "_" + df["UTC Time"].astype(str)
        elif "UTC Time" in df.columns:
            df["utc"] = df["UTC Time"].astype(str)
        else:
            df["utc"] = pd.NA

        # Re-format the time portion to 3 decimals so PC and SD logs match
        def _normalize_utc(s):
            if pd.isna(s) or "_" not in str(s):
                return s
            try:
                d, t = str(s).split("_", 1)
                return f"{d}_{float(t):010.3f}"
            except (ValueError, TypeError):
                return s

        df["utc"] = df["utc"].apply(_normalize_utc)

        keep_cols = ["utc", "Label"] + self.feature_cols

        missing = [c for c in keep_cols if c not in df.columns]
        if missing:
            print(f"WARNING {os.path.basename(path)} missing columns: {missing}")
            for c in missing:
                df[c] = pd.NA

        df = df[keep_cols].copy()
        df["session_id"] = self._session_id_from_filename(path)
        return df

    def load_all(self):
        paths = sorted(glob.glob(os.path.join(self.data_dir, "*.csv")))
        paths = [
            p for p in paths
            if not os.path.basename(p).startswith(".~")
            and not os.path.basename(p).startswith("route_")
            and not os.path.basename(p).startswith("accel_raw_")
        ]

        print(f"Found {len(paths)} CSV files in {self.data_dir}\n")

        dfs = []
        for p in paths:
            try:
                df = self._load_one_file(p)
                n_spoof = (df["Label"] == 1).sum()
                n_legit = (df["Label"] == 0).sum()
                print(f" {os.path.basename(p)[:65]:<65s} "
                      f"rows={len(df):>5d} spoof={n_spoof:>5d} legit={n_legit:>5}")
                dfs.append(df)
            except Exception as e:
                print(f" FAIL {os.path.basename(p)}: {e}")

        if not dfs:
            raise RuntimeError(f"No usable CSVs in {self.data_dir}")

        big = pd.concat(dfs, ignore_index=True)
        print(f"\nCombined: {len(big)} rows from {len(dfs)} files")
        return big

    def add_cross_modal_features(self, df):
        df = self.features.compute_batch(df)

        print(f"\nAdded {len(self.features.FEATURE_NAMES)} cross-modal features:")
        print(f"  motion_disagreement   (binary GPS vs accel motion)")
        print(f"  motion_mismatch       (continuous |Speed - DynMag|)")
        print(f"  speed_per_dyn_mag     (motion style)")
        print(f"  speed_per_jerk_std    (speed vs jerk variability)")
        return df

    # Split by session_id so the model never sees rows from the same recording
    # on both sides of the split
    def split_train_holdout(self, df):
        is_h = df["session_id"].apply(self._is_holdout_session)
        train_df = df.loc[~is_h].copy()
        holdout_df = df.loc[is_h].copy()

        print("\nTrain sessions")
        for sid in sorted(train_df["session_id"].unique()):
            sub = train_df[train_df["session_id"] == sid]
            print(f" {sid[:66]:<66s} rows={len(sub):>5d} "
                  f"spoof={(sub['Label']==1).sum():>5d}")

        print("\nHoldout sessions:")
        for sid in sorted(holdout_df["session_id"].unique()):
            sub = holdout_df[holdout_df["session_id"] == sid]
            print(f" {sid[:66]:<66s} rows={len(sub):>5d} "
                  f"spoof={(sub['Label']==1).sum():>5d}")

        return train_df, holdout_df

    def save(self, train, holdout):
        os.makedirs(self.out_dir, exist_ok=True)
        tp = os.path.join(self.out_dir, "train.csv")
        hp = os.path.join(self.out_dir, "holdout.csv")
        train.to_csv(tp, index=False)
        holdout.to_csv(hp, index=False)

        print("\nWrote:")
        print(f" {tp} rows={len(train):>5d} "
              f"spoof={(train['Label']==1).sum()} "
              f"legit={(train['Label']==0).sum()}")
        print(f" {hp} rows={len(holdout):>5d} "
              f"spoof={(holdout['Label']==1).sum()} "
              f"legit={(holdout['Label']==0).sum()}")
