#######################################################
# 
# ExplainerClassification.py
# Python implementation of the Class ExplainerClassification
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from UBiQTree.classification import ExplainerClassification as _UbiQExplainerClassification


# Re-export of UBiQTree.classification.ExplainerClassification
class ExplainerClassification(_UbiQExplainerClassification):
    pass
