#######################################################
# 
# LGBMClassifier.py
# Python implementation of the Class LGBMClassifier
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import lightgbm as _lgb


# Re-export of lightgbm.LGBMClassifier
class LGBMClassifier(_lgb.LGBMClassifier):
    pass
