#######################################################
# 
# ModelBundle.py
# Python implementation of the Class ModelBundle
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import json
import os
import pickle
from dataclasses import dataclass, field

import lightgbm as lgb


@dataclass
class ModelBundle:
    model: object = None
    scaler: object = None
    feature_list: list = field(default_factory=list)
    track_name: str = ""

    def save(self, path):
        os.makedirs(path, exist_ok=True)

        model_path = os.path.join(path, "model.txt")
        if hasattr(self.model, "booster_"):
            self.model.booster_.save_model(model_path)
        elif isinstance(self.model, lgb.Booster):
            self.model.save_model(model_path)
        else:
            raise ValueError(
                "ModelBundle.save: unsupported model type {}".format(type(self.model))
            )

        with open(os.path.join(path, "scaler.pkl"), "wb") as f:
            pickle.dump(self.scaler, f)

        with open(os.path.join(path, "feature_list.json"), "w") as f:
            json.dump(list(self.feature_list), f, indent=2)

        with open(os.path.join(path, "metadata.json"), "w") as f:
            json.dump({"track_name": self.track_name}, f, indent=2)

    @classmethod
    def load(cls, path):
        model = lgb.Booster(model_file=os.path.join(path, "model.txt"))

        with open(os.path.join(path, "scaler.pkl"), "rb") as f:
            scaler = pickle.load(f)

        with open(os.path.join(path, "feature_list.json")) as f:
            feature_list = json.load(f)

        meta_path = os.path.join(path, "metadata.json")
        track_name = ""
        if os.path.exists(meta_path):
            with open(meta_path) as f:
                track_name = json.load(f).get("track_name", "")

        return cls(
            model=model,
            scaler=scaler,
            feature_list=feature_list,
            track_name=track_name,
        )
