#######################################################
# 
# RandomForestClassifier.py
# Python implementation of the Class RandomForestClassifier
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from sklearn.ensemble import RandomForestClassifier as _SklearnRandomForestClassifier


# Re-export of sklearn.ensemble.RandomForestClassifier
class RandomForestClassifier(_SklearnRandomForestClassifier):
    pass
