#######################################################
# 
# RankingCombiner.py
# Python implementation of the Class RankingCombiner
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import numpy as np

from Pc_backend.Ml_pipeline.CombinedRanking import CombinedRanking


VALID_METHODS = ("rank_sum", "borda", "geometric_mean")


class RankingCombiner:

    def __init__(self, method="rank_sum"):
        if method not in VALID_METHODS:
            raise ValueError(
                "RankingCombiner: method must be one of {}, got {!r}".format(
                    VALID_METHODS, method))
        self.method = method

    def combine(self, shap, ubiq):
        if list(shap.feature_names) != list(ubiq.feature_names):
            raise ValueError(
                "RankingCombiner.combine: feature_names mismatch between "
                "SHAP and UbiQTree results. Re-rank with the same feature list.")

        feature_names = list(shap.feature_names)

        if self.method == "rank_sum":
            combined_ranks, combined_scores = self._rank_sum(
                shap.ranks, ubiq_ranks_from(ubiq))
        elif self.method == "borda":
            combined_ranks, combined_scores = self._borda_count(
                shap.ranks, ubiq_ranks_from(ubiq))
        elif self.method == "geometric_mean":
            combined_ranks, combined_scores = self._geometric_mean(
                shap.mean_abs_shap, np.abs(ubiq.mean))
        else:
            raise RuntimeError("unreachable")

        print(f"\nCombined ranking via {self.method}:")
        print(f"  {'rank':<5s}{'feature':<22s}{'score':>12s}")
        order = np.argsort(combined_ranks)
        for rank_pos, feat_idx in enumerate(order, start=1):
            print(f"  {rank_pos:<5d}{feature_names[feat_idx]:<22s}"
                  f"{combined_scores[feat_idx]:>12.6f}")

        return CombinedRanking(
            feature_names=feature_names,
            combined_ranks=list(combined_ranks),
            combined_scores=list(combined_scores),
            method_used=self.method,
        )

    def _rank_sum(self, shap_ranks, ubiq_ranks):
        scores = np.asarray(shap_ranks) + np.asarray(ubiq_ranks)
        return self._scores_to_ranks(scores, lower_is_better=True), scores

    def _borda_count(self, shap_ranks, ubiq_ranks):
        n = len(shap_ranks)
        shap_points = n - np.asarray(shap_ranks) + 1
        ubiq_points = n - np.asarray(ubiq_ranks) + 1
        scores = shap_points + ubiq_points
        return self._scores_to_ranks(scores, lower_is_better=False), scores

    def _geometric_mean(self, shap_scores, ubiq_scores):
        eps = 1e-12
        scores = np.sqrt(
            (np.asarray(shap_scores) + eps) * (np.asarray(ubiq_scores) + eps))
        return self._scores_to_ranks(scores, lower_is_better=False), scores

    @staticmethod
    def _scores_to_ranks(scores, lower_is_better):
        scores = np.asarray(scores)
        if lower_is_better:
            order = np.argsort(scores)
        else:
            order = np.argsort(-scores)
        ranks = np.zeros(len(scores), dtype=int)
        for rank_pos, feat_idx in enumerate(order, start=1):
            ranks[feat_idx] = rank_pos
        return ranks


def ubiq_ranks_from(ubiq):
    abs_mean = np.abs(np.asarray(ubiq.mean))
    order = np.argsort(-abs_mean)
    ranks = np.zeros(len(abs_mean), dtype=int)
    for rank_pos, feat_idx in enumerate(order, start=1):
        ranks[feat_idx] = rank_pos
    return ranks
