#######################################################
# 
# ShapResult.py
# Python implementation of the Class ShapResult
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass, field

import numpy as np
import pandas as pd


@dataclass
class ShapResult:
    feature_names: list = field(default_factory=list)
    mean_shap: np.ndarray = None
    mean_abs_shap: np.ndarray = None
    ranks: list = field(default_factory=list)

    def ranked_by_mean_abs(self):
        pairs = list(zip(self.feature_names, self.mean_abs_shap))
        return sorted(pairs, key=lambda kv: kv[1], reverse=True)

    def to_dataframe(self):
        return pd.DataFrame({
            "feature": self.feature_names,
            "mean_shap": self.mean_shap,
            "mean_abs_shap": self.mean_abs_shap,
            "rank": self.ranks,
        }).sort_values("mean_abs_shap", ascending=False).reset_index(drop=True)
