#######################################################
# 
# StandardScaler.py
# Python implementation of the Class StandardScaler
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from sklearn.preprocessing import StandardScaler as _SklearnStandardScaler


# Re-export of sklearn.preprocessing.StandardScaler
class StandardScaler(_SklearnStandardScaler):
    pass
