#######################################################
# 
# TrainingPipeline.py
# Python implementation of the Class TrainingPipeline
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import os

import pandas as pd

from Pc_backend.Ml_pipeline.DatasetMerger import DatasetMerger
from Pc_backend.Ml_pipeline.Trainer import Trainer
from Pc_backend.Ml_pipeline.FeatureRanker import FeatureRanker
from Pc_backend.Ml_pipeline.UbiQTreeRanker import UbiQTreeRanker
from Pc_backend.Ml_pipeline.RankingCombiner import RankingCombiner
from Pc_backend.Ml_pipeline.Evaluator import Evaluator
from Pc_backend.Ml_pipeline.ThesisPlots import ThesisPlots


DEFAULT_FEATURE_COLS = [
    "Speed", "HDOP", "Satelites", "Latitude", "Longitude", "Altitude",
    "Roll Degrees", "Pitch Degrees",
    "Dynamic Magnitude", "Jerk", "Jerk Std",
    "Acceleration X", "Acceleration Y", "Acceleration Z",
    "Standard Deviation", "Energy", "Zero Crossings",
]

DEFAULT_HOLDOUT_TOKENS = [
    "Kiwi-Joker-2",
    "(Real Kiwi-Joker)",
    "20260519",
    "190526",
]

# Present in train.csv but excluded from the model. Geographic columns
# leak the session route.
NON_FEATURE_COLS = [
    "utc", "session_id", "Label",
    "Latitude", "Longitude", "Altitude",
    "HDOP", "Satelites",
]


class TrainingPipeline:

    def __init__(self, data_dir, out_dir, model_dir,
                 delta_tolerance=0.01,
                 feature_cols=None,
                 holdout_tokens=None):
        self.data_dir = data_dir
        self.out_dir = out_dir
        self.model_dir = model_dir
        self.delta_tolerance = delta_tolerance

        feature_cols = feature_cols if feature_cols is not None else DEFAULT_FEATURE_COLS
        holdout_tokens = holdout_tokens if holdout_tokens is not None else DEFAULT_HOLDOUT_TOKENS

        self.merger = DatasetMerger(data_dir, out_dir, feature_cols, holdout_tokens)
        self.trainer = Trainer(delta_tolerance=delta_tolerance)
        self.combiner = RankingCombiner(method="rank_sum")
        self.shap_ranker = None
        self.ubiq_ranker = None
        self.evaluator = None
        self.plots = ThesisPlots()

        self._train_df = None
        self._holdout_df = None
        self._X_tr = None
        self._X_val = None
        self._y_tr = None
        self._y_val = None
        self._feature_cols = None
        self._shap_result = None
        self._ubiq_result = None
        self._accum_results = {}
        self._roc_data = {}

    def run(self):
        self._prepare_data()

        baseline_lgb = self.trainer.train_baseline_lgb(
            self._X_tr, self._y_tr, self._X_val, self._y_val)
        baseline_rf = self.trainer.train_baseline_rf(
            self._X_tr, self._y_tr)

        self.shap_ranker = FeatureRanker(baseline_lgb, self._feature_cols)
        self._shap_result = self.shap_ranker.rank(self._X_val)
        self.shap_ranker.plot_summary(
            self._shap_result,
            os.path.join(self.model_dir, "shap", "plots", "shap_summary.png"),
        )

        shap_plots_dir = os.path.join(self.model_dir, "shap", "plots")
        self.plots.shap_importance(
            self.shap_ranker._last_shap_values,
            self.shap_ranker._last_X_val,
            self._feature_cols,
            os.path.join(shap_plots_dir, "shap_importance.png"),
        )
        self.plots.shap_global_uncertainty(
            self.shap_ranker._last_shap_values,
            self._feature_cols,
            os.path.join(shap_plots_dir, "shap_global_uncertainty.png"),
        )
        self.plots.shap_violin_top3(
            self.shap_ranker._last_shap_values,
            self._feature_cols,
            os.path.join(shap_plots_dir, "shap_violin_top3.png"),
        )

        self.ubiq_ranker = UbiQTreeRanker(
            baseline_rf, self._X_tr, self._y_tr, self._feature_cols)
        self._ubiq_result = self.ubiq_ranker.rank(self._X_val)
        self.ubiq_ranker.plot_uncertainty_bars(
            self._ubiq_result,
            os.path.join(self.model_dir, "ubiqtree", "plots", "ubiq_bars.png"),
        )
        self.ubiq_ranker.plot_uncertainty_comparison(
            self._ubiq_result,
            os.path.join(self.model_dir, "ubiqtree", "plots", "ubiq_comparison.png"),
        )

        self.plots.belief_plausibility(
            self._ubiq_result,
            os.path.join(self.model_dir, "ubiqtree", "plots",
                         "ubiq_belief_plausibility.png"),
        )

        combined_plots_dir = os.path.join(self.model_dir, "combined", "plots")
        self.plots.combined_ranking_3panel(
            self._shap_result, self._ubiq_result,
            os.path.join(combined_plots_dir, "combined_ranking_plot.png"),
        )
        self.plots.rank_agreement_scatter(
            self._shap_result, self._ubiq_result,
            os.path.join(combined_plots_dir, "rank_agreement_scatter.png"),
        )

        shap_bundle = self.run_shap_track()
        ubiq_bundle = self.run_ubiqtree_track()
        combined_bundle = self.run_combined_track()

        self._evaluate_track("shap")
        self._evaluate_track("ubiqtree")
        self._evaluate_track("combined")

        Evaluator.plot_roc_comparison(
            [self._roc_data["shap"],
            self._roc_data["ubiqtree"],
            self._roc_data["combined"]],
            os.path.join(self.model_dir, "combined", "plots",
                         "roc_comparison.png"),
        )

        return shap_bundle, ubiq_bundle, combined_bundle

    def run_shap_track(self):
        ranked = [f for f, _ in self._shap_result.ranked_by_mean_abs()]
        return self._train_and_save_track(ranked, "shap")

    def run_ubiqtree_track(self):
        ranked = [f for f, _ in self._ubiq_result.ranked_by_mean_abs()]
        return self._train_and_save_track(ranked, "ubiqtree")

    def run_combined_track(self):
        combined = self.combiner.combine(self._shap_result, self._ubiq_result)
        ranked = combined.top_k_features(k=len(combined.feature_names))
        return self._train_and_save_track(ranked, "combined")

    def _prepare_data(self):
        df = self.merger.load_all()
        df = self.merger.add_cross_modal_features(df)

        numeric_cols = df.select_dtypes(include=['float64']).columns
        df[numeric_cols] = df[numeric_cols].round(6)

        train_df, holdout_df = self.merger.split_train_holdout(df)
        self.merger.save(train_df, holdout_df)

        self._train_df = train_df
        self._holdout_df = holdout_df

        feature_cols = [c for c in train_df.columns if c not in NON_FEATURE_COLS]
        n_before = len(train_df)
        train_df = train_df.dropna(subset=feature_cols).reset_index(drop=True)
        n_dropped = n_before - len(train_df)
        if n_dropped:
            print(f"Dropped {n_dropped} train rows with NaN in feature cols")

        X = train_df[feature_cols].copy()
        y = train_df["Label"].astype(int).values
        self._feature_cols = feature_cols

        self._X_tr, self._X_val, self._y_tr, self._y_val = \
            self.trainer.split_and_normalize(X, y)

    def _train_and_save_track(self, ranked_features, track_name):
        print(f"\n=== Track: {track_name} ===")
        accum = self.trainer.feature_accumulation_curve_lgb(
            self._X_tr, self._y_tr,
            self._X_val, self._y_val,
            ranked_features,
        )
        accum.plot(os.path.join(
            self.model_dir, track_name, "plots", "feature_accumulation.png"))

        self._accum_results[track_name] = accum

        top_k = ranked_features[:accum.optimal_k]
        bundle = self.trainer.train_final_lgb(
            self._X_tr, self._y_tr,
            self._X_val, self._y_val,
            top_k,
            track_name,
        )

        out_path = os.path.join(self.model_dir, track_name)
        bundle.save(out_path)
        print(f"Saved {track_name} bundle to {out_path}")
        return bundle

    def _evaluate_track(self, track_name):
        bundle_path = os.path.join(self.model_dir, track_name)
        evaluator = Evaluator(bundle_path)
        metrics = evaluator.evaluate(self._holdout_df)
        metrics_path = os.path.join(bundle_path, "holdout_metrics.json")
        metrics.to_json(metrics_path)
        print(f"Saved {track_name} holdout metrics to {metrics_path}")

        plots_dir = os.path.join(bundle_path, "plots")
        roc_data = evaluator.plot_roc(
            self._holdout_df,
            os.path.join(plots_dir, "roc.png"),
    )
        self._roc_data[track_name] = roc_data

        self.plots.confusion_matrix(
            metrics,
            os.path.join(plots_dir, "confusion_matrix.png"),
        )
        accum = self._accum_results.get(track_name)
        if accum is not None:
            self.plots.summary_dashboard(
                self._shap_result, accum, metrics,
                os.path.join(plots_dir, "summary_dashboard.png"),
            )

        return metrics


if __name__ == "__main__":
    DATA_DIR = r"C:\Users\sindre\gps-spoofing-and-ai-detection\ml\data\dataset"
    OUT_DIR = r"C:\Users\sindre\gps-spoofing-and-ai-detection\ml\data\processed"
    MODEL_DIR = r"C:\Users\sindre\gps-spoofing-and-ai-detection\ml\models"

    pipeline = TrainingPipeline(DATA_DIR, OUT_DIR, MODEL_DIR)
    pipeline.run()
    print("\nAll three tracks done.")
