#######################################################
# 
# Trainer.py
# Python implementation of the Class Trainer
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import lightgbm as lgb

from Pc_backend.Ml_pipeline.StandardScaler import StandardScaler
from Pc_backend.Ml_pipeline.LGBMClassifier import LGBMClassifier
from Pc_backend.Ml_pipeline.RandomForestClassifier import RandomForestClassifier
from Pc_backend.Ml_pipeline.AccumulationResult import AccumulationResult
from Pc_backend.Ml_pipeline.ModelBundle import ModelBundle


TEST_SIZE = 0.20
RANDOM_STATE = 42
DELTA_TOLERANCE = 0.01

LGBM_PARAMS = dict(
    objective='binary',
    num_leaves=31,
    learning_rate=0.05,
    n_estimators=200,
    class_weight='balanced',
    random_state=RANDOM_STATE,
    verbose=-1,
)

# RF baseline wrapped by UbiQTree's ExplainerClassification
RF_PARAMS = dict(
    n_estimators=100,
    class_weight='balanced',
    random_state=RANDOM_STATE,
    n_jobs=-1,
)


class Trainer:

    def __init__(self, delta_tolerance=DELTA_TOLERANCE):
        self.delta_tolerance = delta_tolerance
        self.scaler = None

    # Stratified 80/20 split, fit StandardScaler on train only
    def split_and_normalize(self, X, y):
        X_tr, X_val, y_tr, y_val = train_test_split(
            X, y,
            test_size=TEST_SIZE,
            stratify=y,
            random_state=RANDOM_STATE,
        )

        print(f"\nTrain split: {len(X_tr)} rows  "
              f"({(y_tr==1).sum()} spoof, {(y_tr==0).sum()} legit)")
        print(f"Val split:   {len(X_val)} rows  "
              f"({(y_val==1).sum()} spoof, {(y_val==0).sum()} legit)")

        scaler = StandardScaler()
        X_tr_scaled = pd.DataFrame(
            scaler.fit_transform(X_tr),
            columns=X_tr.columns,
            index=X_tr.index,
        )
        X_val_scaled = pd.DataFrame(
            scaler.transform(X_val),
            columns=X_val.columns,
            index=X_val.index,
        )

        self.scaler = scaler
        print(f"Scaler fitted on {len(X_tr)} training rows")
        return X_tr_scaled, X_val_scaled, y_tr, y_val

    def train_baseline_lgb(self, X_tr, y_tr, X_val, y_val):
        model = LGBMClassifier(**LGBM_PARAMS)
        model.fit(X_tr, y_tr)

        y_pred = model.predict(X_val)
        acc = accuracy_score(y_val, y_pred)
        print(f"\nBaseline LGBM accuracy on val set (all features): {acc:.4f}")
        return model

    def train_baseline_rf(self, X_tr, y_tr):
        rf = RandomForestClassifier(**RF_PARAMS)
        rf.fit(X_tr, y_tr)
        print(f"Baseline RF trained ({RF_PARAMS['n_estimators']} trees)")
        return rf

    # Train LGBM with the top-k features for k=2..N, record val accuracy
    def feature_accumulation_curve_lgb(self, X_tr, y_tr, X_val, y_val,
                                       ranked_features):
        print("\nFeature accumulation:")
        print(f"  {'k':<4s}{'features used':<60s}{'val accuracy':>14s}")
        k_values = []
        accs = []

        for k in range(2, len(ranked_features) + 1):
            cols = ranked_features[:k]
            model = LGBMClassifier(**LGBM_PARAMS)
            model.fit(X_tr[cols], y_tr)
            y_pred = model.predict(X_val[cols])
            acc = accuracy_score(y_val, y_pred)
            used = ", ".join(cols)
            if len(used) > 58:
                used = used[:55] + "..."
            print(f"  {k:<4d}{used:<60s}{acc:>14.4f}")
            k_values.append(k)
            accs.append(acc)

        max_acc = max(accs)
        result = AccumulationResult(
            k_values=k_values,
            accuracies=accs,
            ranked_features=list(ranked_features),
            max_accuracy=max_acc,
            optimal_k=0,
            delta_tolerance=self.delta_tolerance,
        )
        result.optimal_k = self.select_optimal_k(result)
        return result

    # Smallest k whose accuracy is within delta_tolerance of max
    def select_optimal_k(self, result):
        threshold = result.max_accuracy - self.delta_tolerance
        for k, acc in zip(result.k_values, result.accuracies):
            if acc >= threshold:
                print(f"\nMax accuracy: {result.max_accuracy:.4f}")
                print(f"Threshold (max - {self.delta_tolerance}): {threshold:.4f}")
                print(f"Smallest k that meets threshold: {k}")
                return k
        return result.k_values[-1]

    def train_final_lgb(self, X_tr, y_tr, X_val, y_val, top_k_features,
                        track_name):
        print(f"\n=== Final model: track={track_name}, {len(top_k_features)} features ===")
        for f in top_k_features:
            print(f"  {f}")

        model = LGBMClassifier(**LGBM_PARAMS)
        model.fit(X_tr[top_k_features], y_tr)

        y_pred = model.predict(X_val[top_k_features])
        acc = accuracy_score(y_val, y_pred)
        print(f"Val accuracy on chosen subset: {acc:.4f}")

        return ModelBundle(
            model=model,
            scaler=self.scaler,
            feature_list=list(top_k_features),
            track_name=track_name,
        )
