#######################################################
# 
# TreeExplainer.py
# Python implementation of the Class TreeExplainer
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import shap as _shap


# Alias rather than subclass: shap.TreeExplainer uses __new__ internally
TreeExplainer = _shap.TreeExplainer
