#######################################################
# 
# UbiqResult.py
# Python implementation of the Class UbiqResult
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass, field

import numpy as np
import pandas as pd


@dataclass
class UbiqResult:
    feature_names: list = field(default_factory=list)
    mean: np.ndarray = None
    std: np.ndarray = None
    ci_95: np.ndarray = None
    entropy: np.ndarray = None
    sign_stability: np.ndarray = None
    samples: np.ndarray = None

    def ranked_by_mean_abs(self):
        pairs = list(zip(self.feature_names, np.abs(self.mean)))
        return sorted(pairs, key=lambda kv: kv[1], reverse=True)

    def ranked_by_sign_stability(self):
        pairs = list(zip(self.feature_names, self.sign_stability))
        return sorted(pairs, key=lambda kv: kv[1], reverse=True)

    def to_dataframe(self):
        return pd.DataFrame({
            "feature": self.feature_names,
            "mean": self.mean,
            "std": self.std,
            "ci_low": self.ci_95[:, 0] if self.ci_95 is not None else None,
            "ci_high": self.ci_95[:, 1] if self.ci_95 is not None else None,
            "entropy": self.entropy,
            "sign_stability": self.sign_stability,
        })
