#######################################################
# 
# AccelPacket.py
# Python implementation of the Class AccelPacket
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass


@dataclass
class AccelPacket:
    roll: float = 0.0
    pitch: float = 0.0
    dyn_mag: float = 0.0
    jerk_mag: float = 0.0
    jerk_std: float = 0.0
    accel_x: float = 0.0
    accel_y: float = 0.0
    accel_z: float = 0.0
    accel_std: float = 0.0
    accel_energy: float = 0.0
    accel_zero_cross: float = 0.0
    utc: str = ""
