#######################################################
# 
# GpsPacket.py
# Python implementation of the Class GpsPacket
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass


@dataclass
class GpsPacket:
    label: int = 0
    lat: float = 0.0
    lon: float = 0.0
    alt: float = 0.0
    speed: float = 0.0
    hdop: float = 0.0
    num_sats: int = 0
    course: float = 0.0
    fix: int = 0
    utc: str = ""
