#######################################################
# 
# OnlineClassifier.py
# Python implementation of the Class OnlineClassifier
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from datetime import datetime

import numpy as np
import pandas as pd

from Pc_backend.Ml_pipeline.ModelBundle import ModelBundle
from Pc_backend.Runtime.ClassificationResult import ClassificationResult


SPOOF_THRESHOLD = 0.5


class OnlineClassifier:

    def __init__(self, bundle_path):
        self.bundle = ModelBundle.load(bundle_path)
        self.feature_list = list(self.bundle.feature_list)
        self.scaler_features = list(self.bundle.scaler.feature_names_in_)

    def classify(self, features):
        missing = [c for c in self.scaler_features if c not in features]
        if missing:
            return ClassificationResult(
                prediction=-1,
                confidence=0.0,
                features_used=dict(features),
                timestamp=datetime.now().isoformat(),
            )

        X = pd.DataFrame([{c: features[c] for c in self.scaler_features}])
        X_scaled = pd.DataFrame(
            self.bundle.scaler.transform(X),
            columns=self.scaler_features,
        )
        X_for_model = X_scaled[self.feature_list]

        proba = self.bundle.model.predict(X_for_model)[0]
        prediction = int(proba >= SPOOF_THRESHOLD)
        confidence = float(proba if prediction == 1 else 1.0 - proba)

        return ClassificationResult(
            prediction=prediction,
            confidence=confidence,
            features_used={c: float(features[c]) for c in self.feature_list},
            timestamp=datetime.now().isoformat(),
        )

    def _select_features(self, features):
        return [features[c] for c in self.scaler_features]

    def _normalize(self, values):
        arr = np.asarray(values).reshape(1, -1)
        return self.bundle.scaler.transform(arr).ravel()
