#######################################################
# 
# PairedRow.py
# Python implementation of the Class PairedRow
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from dataclasses import dataclass, field


@dataclass
class PairedRow:
    gps: object = None
    accel: object = None
    features: dict = field(default_factory=dict)
    classification: object = None
    timestamp: str = ""
