#######################################################
# 
# PcLogger.py
# Python implementation of the Class PcLogger
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

from Pc_backend.Runtime.CsvWriter import CsvWriter


BASE_HEADER = [
    "Time", "UTC Time", "Label",
    "Latitude", "Longitude", "Altitude",
    "Speed", "HDOP", "Satelites", "Course", "Fix",
    "Accel UTC",
    "Roll Degrees", "Pitch Degrees",
    "Dynamic Magnitude", "Jerk", "Jerk Std",
    "Acceleration X", "Acceleration Y", "Acceleration Z",
    "Standard Deviation", "Energy", "Zero Crossings",
]

CLASSIFIER_HEADER = ["Prediction", "Confidence"]


class PcLogger:

    def __init__(self, csv_path, with_classifier=False):
        self.csv_path = csv_path
        self.with_classifier = with_classifier
        self.writer = CsvWriter(csv_path)
        self.writer.open(mode="w", newline="")
        self.write_header()
        self.writer.close()
        self.writer.open(mode="a", newline="")

    def write_header(self):
        header = list(BASE_HEADER)
        if self.with_classifier:
            header.extend(CLASSIFIER_HEADER)
        self.writer.writerow(header)

    def write_row(self, row):
        gps = row.gps
        accel = row.accel

        base = [
            row.timestamp,
            gps.utc,
            gps.label,
            gps.lat, gps.lon, gps.alt,
            gps.speed, gps.hdop, gps.num_sats, gps.course, gps.fix,
        ]

        if accel is not None:
            base.extend([
                accel.utc,
                accel.roll, accel.pitch,
                accel.dyn_mag, accel.jerk_mag, accel.jerk_std,
                accel.accel_x, accel.accel_y, accel.accel_z,
                accel.accel_std, accel.accel_energy, accel.accel_zero_cross,
            ])
        else:
            base.extend(["", "", "", "", "", "", "", "", "", "", "", ""])

        if self.with_classifier:
            if row.classification is not None and row.classification.prediction >= 0:
                base.extend([
                    row.classification.prediction,
                    "{:.4f}".format(row.classification.confidence),
                ])
            else:
                base.extend(["", ""])

        self.writer.writerow(base)

    def close(self):
        self.writer.close()
