#######################################################
# 
# socket.py
# Python implementation of the Class socket
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import socket as _stdlib_socket


socket = _stdlib_socket.socket
AF_INET = _stdlib_socket.AF_INET
SOCK_DGRAM = _stdlib_socket.SOCK_DGRAM
