#######################################################
# 
# StreamPairer.py
# Python implementation of the Class StreamPairer
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

import time

from Pc_backend.Runtime.PairedRow import PairedRow


DEFAULT_STALE_THRESHOLD_S = 15.0


class StreamPairer:

    def __init__(self, stale_threshold_s=DEFAULT_STALE_THRESHOLD_S):
        self.stale_threshold = stale_threshold_s
        self.latest_accel = None
        self.latest_accel_time = 0.0

    def on_accel(self, packet):
        self.latest_accel = packet
        self.latest_accel_time = time.time()

    def on_gps(self, packet):
        row = PairedRow(gps=packet, timestamp=self._iso_now())

        if self.latest_accel is not None and not self._is_accel_stale():
            row.accel = self.latest_accel
        else:
            row.accel = None

        return row

    def _is_accel_stale(self):
        if self.latest_accel is None:
            return True
        age = time.time() - self.latest_accel_time
        return age >= self.stale_threshold

    @staticmethod
    def _iso_now():
        from datetime import datetime
        return datetime.now().isoformat()
