#######################################################
# 
# LoRaTx.py
# Python implementation of the Class LoRaTx
# Generated by Enterprise Architect
# Created on:      13-May-2026 10:20:26 AM
# Original author: sindre
# 
#######################################################

#
# LoRaTx.py
# Sends GPS and accel packets over LoRa on two separate EU868 channels.
# GPS goes on 868.1 MHz, accel on 868.3 MHz so the streams don't collide.
#

from network import LoRa
import socket
import struct


class LoRaTx:

    PACKET_GPS = 0
    PACKET_ACCEL = 1

    FREQ_GPS = 868100000
    FREQ_ACCEL = 868300000

    # GPS_FORMAT tail: I = utc_date (DDMMYY as uint32), f = utc_time (HHMMSS.SSS as float).
    # The PC receiver uses these to log real GPS UTC for both legit and spoofed streams.
    GPS_FORMAT = 'BBfffffifiIf'

    # ACCEL_FORMAT mirrors GPS_FORMAT's UTC tail so the PC can align accel rows
    # with GPS rows on a shared timeline. When the device has no fix yet, the
    # tail is zeros and the PC pairs by wall-clock arrival.
    ACCEL_FORMAT = 'BfffffffffffIf'

    def __init__(self, tx_power=14, spreading_factor=10):
        # EU868 region radio init
        self.lora = LoRa(mode=LoRa.LORA, region=LoRa.EU868)

        # Start tuned to the GPS frequency. send_accel() swaps to ACCEL and back.
        self.lora.frequency(self.FREQ_GPS)
        self.lora.bandwidth(LoRa.BW_125KHZ)
        self.lora.sf(spreading_factor)
        self.lora.tx_power(tx_power)

        self.s = socket.socket(socket.AF_LORA, socket.SOCK_RAW)
        self.s.setblocking(False)

        self.packets_sent = 0
        self.send_failures = 0

    def _send_packet(self, packed):
        # Blocking send with success/fail counting
        try:
            self.s.setblocking(True)
            bytes_sent = self.s.send(packed)
            self.s.setblocking(False)

            if bytes_sent == len(packed):
                self.packets_sent += 1
                return True
            else:
                self.send_failures += 1
                print("Partial send: {}/{}".format(bytes_sent, len(packed)))
                return False

        except Exception as e:
            self.send_failures += 1
            print("LoRa send fail: {}".format(e))
            return False

    @staticmethod
    def _parse_utc(gps_data):
        # Pull UTC fields out of a GpsParser.read() dict. Defaults to (0, 0.0)
        # when the dict is None or fields aren't set yet. The PC treats (0, 0.0)
        # as "no UTC, pair by wall clock".
        utc_date_int = 0
        utc_time_float = 0.0
        if not gps_data:
            return utc_date_int, utc_time_float
        try:
            utc_date_raw = gps_data.get('utc_date', '') if hasattr(gps_data, 'get') else ''
        except Exception:
            utc_date_raw = ''
        try:
            utc_time_raw = gps_data.get('utc_time', '') if hasattr(gps_data, 'get') else ''
        except Exception:
            utc_time_raw = ''
        try:
            utc_date_int = int(utc_date_raw) if utc_date_raw else 0
        except (ValueError, TypeError):
            utc_date_int = 0
        try:
            utc_time_float = float(utc_time_raw) if utc_time_raw else 0.0
        except (ValueError, TypeError):
            utc_time_float = 0.0
        return utc_date_int, utc_time_float

    def send_gps(self, gps_data, label):
        # Pack a GPS dict and send on FREQ_GPS
        try:
            utc_date_int, utc_time_float = self._parse_utc(gps_data)

            packed = struct.pack(
                self.GPS_FORMAT,
                self.PACKET_GPS,
                label,
                gps_data['lat'],
                gps_data['lon'],
                gps_data['alt'],
                gps_data['speed'],
                gps_data['hdop'],
                gps_data['sats'],
                gps_data['course'],
                gps_data['fix'],
                utc_date_int,
                utc_time_float,
            )
            return self._send_packet(packed)

        except Exception as e:
            print("GPS pack error: {}".format(e))
            return False

    def send_accel(self, accel_data, gps_data_for_utc=None):
        # Swap to ACCEL frequency, send, swap back to GPS frequency so the
        # next send_gps() doesn't drift to the accel channel.
        try:
            self.lora.frequency(self.FREQ_ACCEL)

            def safe(val):
                return val if val is not None else 0.0

            utc_date_int, utc_time_float = self._parse_utc(gps_data_for_utc)

            packed = struct.pack(
                self.ACCEL_FORMAT,
                self.PACKET_ACCEL,
                accel_data['roll'],
                accel_data['pitch'],
                safe(accel_data['dyn_mag']),
                safe(accel_data['jerk_mag']),
                safe(accel_data['jerk_std']),
                safe(accel_data['accel_x']),
                safe(accel_data['accel_y']),
                safe(accel_data['accel_z']),
                safe(accel_data['accel_std']),
                safe(accel_data['accel_energy']),
                safe(accel_data['accel_zero_cross']),
                utc_date_int,
                utc_time_float,
            )
            result = self._send_packet(packed)
            self.lora.frequency(self.FREQ_GPS)
            return result

        except Exception as e:
            print("Accel pack error: {}".format(e))
            # Best-effort restore on error so the next GPS send still works
            try:
                self.lora.frequency(self.FREQ_GPS)
            except Exception:
                pass
            return False

    def get_stats(self):
        total = self.packets_sent + self.send_failures
        return {
            'packets_sent': self.packets_sent,
            'send_failures': self.send_failures,
            'success_rate': self.packets_sent / total if total > 0 else 0,
        }
